src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/QuerySubscriber/UsesPaginator.php
https://github.com/KnpLabs/KnpPaginatorBundle/issues/276#issuecomment-59019534
=> adding manual hinting for UsesPaginator subscriber

src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php
Resolve https://github.com/KnpLabs/KnpPaginatorBundle/issues/357
I did not add tests because Doctrine is supported in version 2.4 - embeddable was added in 2.5.
=> Fix embeddable sorting

README.md, composer.json, tests/Test/Fixture/Document/Article.php, tests/Test/Fixture/Document/PHPCR/Article.php
More info in the commit messages.
=> Fix some crashes in the test suite under PHP7

.travis.yml, README.md, composer.json, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, src/Knp/Component/Pager/Pagination/AbstractPagination.php, src/Knp/Component/Pager/Pagination/PaginationInterface.php, src/Knp/Component/Pager/Paginator.php, src/Knp/Component/Pager/PaginatorInterface.php, tests/Test/Fixture/Document/Article.php, tests/Test/Pager/Pagination/AbstractPaginationTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/QueryTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/WhitelistTest.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ODM/MongoDB/WhitelistTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/QueryTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/WhitelistTest.php
@polc Thank you for your quick merge of https://github.com/KnpLabs/knp-components/pull/177. I realized that there will be tons of conflict in your branch though, so I solved them for you
=> Merge master to feature/use-psr7

src/Knp/Component/Pager/Pagination/AbstractPagination.php, src/Knp/Component/Pager/Pagination/PaginationInterface.php
Revert change done in https://github.com/KnpLabs/knp-components/pull/176.
=> Revert "Merge pull request #176 from garak/fix-interface"

composer.json, src/Knp/Component/Pager/Event/ItemsEvent.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, src/Knp/Component/Pager/Pagination/AbstractPagination.php, src/Knp/Component/Pager/Pagination/PaginationInterface.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/WhitelistTest.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ODM/MongoDB/WhitelistTest.php
Hopefully this should fix all conflicts. My branch is mergable with 2.0 of this repo, so should work.
=> Merge 2.0 into feature/use-psr7

src/Knp/Component/Pager/Event/Subscriber/Paginate/PropelQuerySubscriber.php
PaginatorInterface was not included in this file...
=> Fixes missing Use statement

src/Knp/Component/Pager/Pagination/AbstractPagination.php, src/Knp/Component/Pager/Pagination/PaginationInterface.php
=> Problem with pagination interface

composer.json, src/Knp/Component/Pager/Event/AfterEvent.php, src/Knp/Component/Pager/Event/BeforeEvent.php, src/Knp/Component/Pager/Event/Event.php, src/Knp/Component/Pager/Event/ItemsEvent.php, src/Knp/Component/Pager/Event/PaginationEvent.php, src/Knp/Component/Pager/Paginator.php
This is an improved version of PR #212 
This will fix issue #213
=> fix event related deprecations

src/Knp/Component/Pager/Event/BeforeEvent.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/PropelQuerySubscriber.php
=> Fix cases of null Request

.travis.yml, composer.json, tests/Test/Pager/Pagination/AbstractPaginationTest.php, tests/Test/Pager/Pagination/CustomParameterTest.php, tests/Test/Pager/Pagination/PaginationInterfaceTest.php, tests/Test/Pager/Pagination/SlidingTest.php, tests/Test/Pager/Pagination/TraversableItemsTest.php, tests/Test/Pager/PaginatorTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/QueryTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/WhitelistTest.php, tests/Test/Pager/Subscriber/Filtration/FiltrationSubscriberTest.php, tests/Test/Pager/Subscriber/Paginate/ArrayTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/CollectionTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/DBALQueryBuilderTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ODM/MongoDB/GridFsTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ODM/MongoDB/QueryBuilderTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ODM/MongoDB/QueryTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ODM/PHPCR/QueryBuilderSubscriberTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ODM/PHPCR/QuerySubscriberTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ORM/AdvancedQueryTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ORM/CompositeKeyTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ORM/QueryBuilderTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ORM/QueryTest.php, tests/Test/Pager/Subscriber/Paginate/ElasticaTest.php, tests/Test/Pager/Subscriber/Paginate/PaginationSubscriberTest.php, tests/Test/Pager/Subscriber/Paginate/SolariumQuerySubscriberTest.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php, tests/Test/Pager/Subscriber/Sortable/SolariumQuerySubscriberTest.php, tests/Test/Pager/Subscriber/Sortable/SortableSubscriberTest.php, tests/Test/Tool/QueryAnalyzer.php
This will fix issue #227 
Also, allow php 7.4 to fail (not due to this library, doctrine annotations are to blame)
=> switch to psr-4

composer.json
Fix some inconsistencies with sorting and constraints.
Also, normalize (using [composer normalize](https://github.com/localheinz/composer-normalize))
=> improve composer.json

src/Knp/Component/Pager/Paginator.php
Related to #228 and #229 
The requestStack can have a list with no request objects when the container has been accessed before a request is sent to the Symfony kernel.
This can result in a null reference when trying to get properties from the request query.
I stumbled upon this one when I am using services in my tests before a request is sent.
=> Do not set the request in constructor

src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php
This should fix https://github.com/KnpLabs/KnpPaginatorBundle/issues/630
=> check parameter before calling `has`

src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/QueryTest.php
This should fix issue https://github.com/KnpLabs/KnpPaginatorBundle/issues/635
=> check if sort param is a string

.php_cs, docs/pager/usage.md, src/Knp/Component/Pager/Event/Subscriber/Paginate/Callback/CallbackSubscriber.php, src/Knp/Component/Pager/Paginator.php, src/Knp/Component/Pager/PaginatorInterface.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/CollectionTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/QueryTest.php
This should fix cases when Legacy dispatcher is not available
=> fix dispatcher on Symfony 3.4

docs/pager/config.md
Updating docs to reflect [PR#260](https://github.com/KnpLabs/knp-components/pull/260) changes.
=> update docs: add pageOutOfRange option

CHANGELOG.md, composer.json, docs/pager/config.md, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, src/Knp/Component/Pager/Paginator.php, src/Knp/Component/Pager/PaginatorInterface.php, tests/Test/Pager/Pagination/AbstractPaginationTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/AllowListTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ODM/MongoDB/AllowListTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/AllowListTest.php
=> remove "whitelist" term

src/Knp/Component/Pager/Paginator.php
=> fix dispatcher check

src/Knp/Component/Pager/Paginator.php
This change fixes an issue introduced in version 2.4.1 with PR #267 
Related issue : #270
=> Fix dispatcher compatibility check for SF < 4.3

CHANGELOG.md, src/Knp/Component/Pager/Paginator.php
Fixed 2 minor typo's regarding `EventDispatcher`
=> Fixed typo's

src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query/WhereWalker.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/QueryTest.php
I'm taking over #164 for @adrienbrault.  I've rebased his commits on top of master and made a few minor adjustments.  Is there anything else that you would like to see done for this to be merged?
=> Fix ORM where in with numeric values on string fields

src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query/WhereWalker.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/QueryTest.php
I'm also taking over #165 for @adrienbrault.  Is there anything else that needs to be done for this PR?
=> Allow ORM case insensitive string filtering

src/Knp/Component/Pager/Event/Subscriber/Paginate/SolariumQuerySubscriber.php
=> Fix results with Solarium on PHP 8

src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php
Add an early return and check for "filterParam" (and "filterValue") parameter existence before trying to get them
=> check parameter before getting it

src/Knp/Component/Pager/Pagination/AbstractPagination.php, src/Knp/Component/Pager/Pagination/PaginationInterface.php, src/Knp/Component/Pager/Pagination/SlidingPagination.php
=> Add template docblocks for pagination

src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query/WhereWalker.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/Query/OrderByWalker.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, src/Knp/Component/Pager/Exception/InvalidValueException.php
=> introduce new internal exception

.github/workflows/build.yaml, composer.json, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query/WhereWalker.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/DBALQueryBuilderSubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/Query/OrderByWalker.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, src/Knp/Component/Pager/Paginator.php, tests/Test/Fixture/Entity/Composite.php, tests/Test/Mock/CustomParameterSubscriber.php, tests/Test/Pager/Pagination/DefaultLimitOptionTest.php, tests/Test/Pager/Pagination/TraversableItemsTest.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/ORM/AdvancedQueryTest.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/QueryTest.php, tests/Test/Tool/BaseTestCaseORM.php, tests/Test/Tool/QueryAnalyzer.php
I just run "inspect code" in phpStorm and found some details to polish.
Plus: new config for actions, it should prevent duplicate builds when tagging
=> improve code
