KnpLabs/knp-components

doc/pager/config.md
I got this exception on sorting: *"Cannot select distinct identifiers from query with LIMIT and ORDER BY on a column from a fetch joined to-many association. Use output walkers."* and it took me hours to find out, what the reason was and that the `Paginator` option `wrap-queries` must be used to use a subquery for distinct select, which prevents this exception.
So I'd like to extend the documentation of that option to help others with the same issue (also mentioned in KnpLabs/KnpPaginatorBundle#106).
=> Extended documentation to prevent exception when ordering on fetch joined to-many association

doc/pager/config.md, doc/pager/usage.md, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/Query/OrderByWalker.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Paginator.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/QueryTest.php, tests/Test/Tool/BaseTestCaseORM.php
In one of my projects I need sorting by multiple fields and it is requested by  others (see KnpLabs/KnpPaginatorBundle#255), too. So I have extended the Paginator, QuerySubscriber and the OrderByWalker.
I have chosen an implementation which is not the nicest, but it keeps backward compatiblity. All tests are passing.
Example how to use this feature:
```php
$pagination = $paginator->paginate(
$queryBuilder,
$page,
$pageSize,
array(
'defaultSortFieldName' => ['user.lastname', 'user.firstname'],
'defaultSortDirection' => 'asc'
)
);
```
I can only provide a solution for Doctrine's ORM. I hope this is no problem.
=> Implemented sorting by multiple fields for paginator (only ORM)

.travis.yml
The mongo extension is not available for these versions, so the ODM cannot be installed
=> Fix the composer install for PHP 7 and HHVM

src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php
usage of `isset` for testing existence of array keys is not recommended and may not work on php 5.6
=> Fix array key existance testing

tests/Test/Pager/Subscriber/Paginate/Doctrine/ORM/CompositeKeyTest.php
I was facing a bug while paginating a Doctrine entity that had a composite primary key and getting this exception:
Single id is not allowed on composite primary key in entity [...]
After poking in the code, I actually found that the exception was being thrown by Doctrine, and there was already a test for that. To my amusement, the test was passing. I tried to do in my code exactly what the test was doing, but no dice.
So I poked a little bit more and discovered that the CompositeKeyTest was running with an empty schema, and that's why it succeded and my code didn't. It took me to just populate the testing schema with some fixtures for the test to fail just like my code.
After a while, I was able to make it work using some crazy hint which I am not sure if it works generally, but worked …
=> Update the CompositeKeyTest to use a populated schema.

src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SortableSubscriber.php
Hi,
Relating [some issues reported](https://github.com/KnpLabs/KnpPaginatorBundle/issues/209), I wrote an ArraySubscriber to allow arrays to be sortable.
I added reflection checks to ensure sort attribute getter would be available on the target entity.
Regarding the implementation, I preferred use 2 distinct callbacks (sortAsc and sortDesc). Although sharing 99% of the code I wanted to avoid "if" check in callback, especially on the large chunks of data.
Let me know if it suits you, or if you have any suggestion to improve.
I currently use Knp-components on a production project, and if it's ok for you it would be great to embed this as a native part.
Cheers for your work,
Nicolas
=> - Add event subscriber to allow array to be sortable

src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/QuerySubscriber/UsesPaginator.php
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes|
Fix of the DISTINCT option.
Since 1.3.0 (this commit https://github.com/KnpLabs/knp-components/commit/861c2a0b9b816be7e7f0b4106aa6be3f60e86226), the distinct option doesn't have the same effect.
**Before 1.3.0**
**distinct: false**
**distinct: true**
-----
**1.3.3 without correction**
**distinct: false**
**distinct: true**
-----
**1.3.3 with correction**
**distinct: false**
**distinct: true**
See doctrine documentation : http://doctrine-orm.readthedocs.org/en/latest/tutorials/pagination.html
=> Corrected distinct option

src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/DBALQueryBuilderSubscriber.php
This is proposed fix to [#149](https://github.com/KnpLabs/knp-components/issues/149)
OrderBy Query Builder part is removed before count query is executed. This fixes MSSQL error when doing count from a VIEW without result limit. It also speeds up count query significantly since order by is not in effect.
=> DBALQueryBuilderSubscriber orderBy query part is removed at count query

src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/DBALQueryBuilderSubscriber.php
Renamed 'ololoshke_trololoshke' alias at count table name to 'dbal_count_tbl' in DBAL Query Builder Subscriber.
This fixes [#123](https://github.com/KnpLabs/knp-components/issues/123) Scary "ololoshke_trololoshke" at the end of some queries. It makes easier understanding of query log.
=> Fixed ololoshke_trololoshke alias at count table name

src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php
If array of Objects don't have object with key 0, I got Notice.
`
Notice: Undefined offset: 0
in vendor/knplabs/knp-components/src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php at line 45
`
My fix resolve this bug
=> fix ArraySubscriber

.travis.yml
Current Travis documentations states:
> The OpenSSL extension is switched off on php 5.3.3 because of compilation problems with OpenSSL 1.0.
This is why a good share of PRs is broken.
=> Remove PHP 5.3.3 from build matrix

src/Knp/Component/Pager/Event/Subscriber/Filtration/FiltrationSubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/PaginationSubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SortableSubscriber.php, tests/Test/Pager/Subscriber/Filtration/FiltrationSubscriberTest.php, tests/Test/Pager/Subscriber/Paginate/PaginationSubscriberTest.php, tests/Test/Pager/Subscriber/Sortable/SortableSubscriberTest.php
Fixes issue #151, by adding state to the lazy-loading event subscribers.
This prevents multiple calls to `Paginator#paginate()` from adding duplicate subscribers to the Event Dispatcher, which can manifest as a memory leak if paginate is repeatedly called.
By putting the state inside the lazy-loading Event Subscribers this keeps the lazy-load mechanism in the domain of the subscriber, leaving the Paginator agnostic to the method used to populate the EventDispatcher.
Tests have been added to confirm this behaviour.
=> Fix memory leak due to Lazy-Loading subscribers

composer.json, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php
The only data structure currenty ArraySubscriber is able to sort is `object[]`, where object MUST have public `get{sortPropertyName}` method. This PR utilizes symfony propertyaccess component instead, which allows to sort pure array, nested structure, objects with issers, __call methods, objects without any getter but with pulic properties, etc. 
Besides this main feature of this PR I changed some things, like I uncommented whitelist, turned strtolower into mb_strtolower for utf support, introduced ability to change built in sorting function with custom one and allowed to sort by other data types than strings, such as dates
=> Utilize PropertyAccess component for sorting arrays

src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query/WhereWalker.php
When you perform the filter based on columns of separate tables joined with join, the error is displayed:
There is no component aliased by [ x] in the given Query
Scenario (OneToMany):
Maker  1:N Product
Properties considered:
Maker 
- name
Product
- model
Wanting to filter based on the product "model" property but also considering the "name" of the maker.
Twig
{{ knp_pagination_filter(pagination, {'p.model, m.name':''}) }}
QueryBuilder
$qb->select('p')
->from'AppBundle\Entity\Product', 'p')
->join('p.maker', 'm', 'WITH')
->orderBy('p.id', 'desc');
When executed, the displayed error:
"There is no component aliased by [ m] in the given Query"
The error is raised because the key generated with the alias "m" is not found in the "components" array, but the key is generated with a blank before …
=> Filtration with join: There is no component aliased by [ x] in the given Query

src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/Query/Helper.php
We need to clone the parameters for this query or the parameters could change if the original query's parameters are changed.
This is how doctrine does it. 
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Pagination/Paginator.php#L212
To bad that method isn't static.
=> Clone the parameters too since they are an object

src/Knp/Component/Pager/Pagination/AbstractPagination.php, src/Knp/Component/Pager/Pagination/PaginationInterface.php
Use case: you typehint a method to return a `PaginationInterface`, then you use the results in a `foreach` loop.
Example:
```php
function foo(): PaginationInterface
{
$pagination = '...';
return $pagination;
}
$pagination = foo();
foreach ($pagination as $item) {
// ...
}
```
if you do a static analysis on the example code, you get a warning because the `foreach` loop is not using an Iterator. The same applies if you want to do a `count($paginator)`
This PR is solving the question, moving the interfaces from `AbstractPagination` to `PaginationInterface`
=> move interfaces to PaginationInterface

.travis.yml, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/QuerySubscriber/UsesPaginator.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, src/Knp/Component/Pager/Paginator.php, src/Knp/Component/Pager/PaginatorInterface.php, tests/Test/Pager/Pagination/AbstractPaginationTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/QueryTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/WhitelistTest.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ODM/MongoDB/WhitelistTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/QueryTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/WhitelistTest.php
Replacing magic strings for more safety in both user space code and knp-components code.
=> replace common magic strings with constants

src/Knp/Component/Pager/Event/ItemsEvent.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php
Before, each sorting listener is called, even when the data has already been sorted. Now we set a boolean in `customPaginationParams`.
=> Fix Elastica & Solarium sort

src/Knp/Component/Pager/Paginator.php
Hello,
It's finally time to fix the long lasting issue that is spamming our sentry since year(s) :D 
```
ErrorException
A non well formed numeric value encountered
```
Forcing the cast to int finally fixes this issue that occurs randomly on old browser (maybe caused by bots).
=> Fix "A non well formed numeric value encountered"

composer.json
Hi guys!
I'd just like to remove some noise when installing. All of these suggests are unnecessary: they don't guide you to install another library in order to add a new feature to this library. It's really the *other* direction: you will already have `doctrine/orm` installed, and then you will install this library so that you can paginate it.
Cheers!
=> Remove unnecessary suggests that are self-evident

src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/Query/WhereInWalker.php
This was relevant for Doctrine ORM < 2.2, but paginator now requires ~2.4
=> Remove old InExpression workaround

src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php
This is a fix for https://github.com/KnpLabs/KnpPaginatorBundle/issues/494 (see [this comment](https://github.com/KnpLabs/KnpPaginatorBundle/issues/494#issuecomment-419145778)) to still be able to sort entries when the sort field is on a relation.
This relation can be `null` (because the DB column of the FK is set to `NULL`), so in this case we should still be able to sort items by setting them to the first or the last position (depends on the sort direction).
=> [RFR] be able to sort on NULL relation with PropertyAccessor

src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, tests/Test/Fixture/Document/Article.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ODM/MongoDB/QueryTest.php
Sorting with `['status+created_at' => 'desc']` does not work with ODM. 
But sorting with `['status' => 'desc', 'created_at' => 'desc']` does work.
My use case was that I needed to sort articles by date desc, but having the published ones first and closed ones after. It works with the changes I made in this `QuerySubscriber.php` file.
=> Fixed multi sort for ODM

doc/pager/intro.md, src/Knp/Component/Pager/Event/Subscriber/Paginate/Callback/CallbackPagination.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Callback/CallbackSubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/PaginationSubscriber.php, tests/Test/Pager/Subscriber/Paginate/Callback/CallbackTest.php, tests/Test/Pager/Subscriber/Paginate/PaginationSubscriberTest.php
Since there is [pagination support](https://github.com/KnpLabs/knp-components/tree/master/src/Knp/Component/Pager/Event/Subscriber/Paginate) for:
* Arrays
* Elastica Query
* Proper
* Solarium
* Doctrine
Nowadays hexagonal architectures and Domain-Driven Design becomes more and more popular. This implicates to have some abstraction to repositories of data. It's code quality breach to expose implementation details and have pagination over it.
The proposition is to implement an interface being able to paginate over custom callback functions (one for get count, one for get items by limit/offset).
Note: Please squash merge.
Example usage:
```php
$count = function () {
// return count from repository
};
$items = function ($offset, $limit) {
// return data from repository using offet and limit …
```
=> Callback pagination

src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php
Fixes https://github.com/KnpLabs/knp-components/issues/225
As pointed out by @johonunu, the `SolariumQuerySubscriber` only checked if the array had 2 items and then it set `$event->setCustomPaginationParameter('sorted', true);` as if it was handled.
This is just moving the `if` statement to the first one.
=> Fix sorting with 2 items

README.md, composer.json
Adds Symfony 5 to the allowed versions of Composer dependencies.
Please note that at the time of submitting this, the `doctrine/mongodb-odm` dependency hasn't added support for Symfony 5 yet.
=> Add Symfony 5 support

src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/CollectionSubscriber.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/CollectionTest.php
CollectionSubscriber is the only pagination subscriber that uses a Doctrine ArrayCollection as its item store. All other subscribers use plain PHP arrays.
PHP 7.4 has a BC break for how ArrayObjects are handled and now current() no longer returns the current item in the ArrayObject.
This fix changes CollectionSubscriber to use a plain PHP array as its item store and also adds a test to confirm that you can iterate over the CollectionArray using foreach().
=> Fix PHP 7.4 ArrayObject BC Break

src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query/WhereWalker.php
Related issue : https://github.com/KnpLabs/KnpPaginatorBundle/issues/631
This fix a bug where embedabble fields were not correctly handled. 
eg: 
``` php
// with $column = 'e.address.alias'
$parts = explode('.', $column); // ['e', 'address', 'society']
$field = end($parts); // expect 'address.society', but get 'society'
```
Bug was already fixed for sorting here : https://github.com/KnpLabs/knp-components/pull/142
=> Fix embeddable filtering

src/Knp/Component/Pager/Paginator.php
Starting from Symfony 5.1, LegacyEventDispatcherProxy is deprecated.
To avoid deprecation warning, we should rely on the presence of old Event class, instead on the possible presence of LegacyEventDispatcherProxy class.
=> avoid using deprecated legacy dispatcher

src/Knp/Component/Pager/Exception/PageNumberOutOfRangeException.php, src/Knp/Component/Pager/Paginator.php, src/Knp/Component/Pager/PaginatorInterface.php, tests/Test/Pager/Pagination/PreventPageOutOfRangeOptionTest.php
This PR adds an optional flag to enforce valid page number and limit. Negative page number is replaced with 1; too big page number is replaced with the last page; negative number of items per page is replaced with default.
The functionality is disabled by default.
This feature was requested in `KnpPaginatorBundle` [several](https://github.com/KnpLabs/KnpPaginatorBundle/issues/477) [times](
https://github.com/KnpLabs/KnpPaginatorBundle/issues/393).
Once this is merged I will create wrapper functionality in the bundle.
=> add an option for replacing invalid/out of range page numbers

docs/pager/usage.md, src/Knp/Component/Pager/Paginator.php, src/Knp/Component/Pager/PaginatorInterface.php, tests/Test/Pager/Pagination/DefaultLimitOptionTest.php
Addressing the #105 
- Default limit value will be set in $defaultOptions, not hardcoded in function declaration.
- Explicitly passing $limit as an argument will work as previously.
- Passing null and getting default limit will be possible while setting other options, like
`$paginator->paginate($query, 1, null, [])`;
- Later with a wrapper functionality in the `KnpPaginatorBundle` default limit will be configurable globally, as other default options.
=> make default limit value to be set in default options

src/Knp/Component/Pager/Paginator.php, tests/Test/Pager/Pagination/PreventPageOutOfRangeOptionTest.php
Hello,
If `$pageOutOfRangeOption === PaginatorInterface::PAGE_OUT_OF_RANGE_FIX` is set as option to paginate, then an exception is thrown `LogicException : Invalid item per page number. Limit: 10 and Page: 0, must be positive non-zero integers` because the above condition perform again `Paginator::paginate` with `int $page = 0`;
If `$items->count` is 0, then result from `ceil` is always 0.
I think it's worth checking how many elements our `$itemsEvent` has in this case.
\cc @garak WDYT ?
=> Fix PAGE_OUT_OF_RANGE_FIX when is set for empty date.

.travis.yml, src/Knp/Component/Pager/Exception/PageNumberOutOfRangeException.php, src/Knp/Component/Pager/Paginator.php, tests/Test/Pager/Pagination/PreventPageOutOfRangeOptionTest.php
Hello,
When using `page_out_of_range: 'throwException'` you can't figure out which is the last page, so this PR adds method`getMaxPageNumber` to PageNumberOutOfRangeException, so you can redirect to last page if you'll like. 
~~Also trying the fix the deprecation message with `LegacyEventDispatcherProxy` on sf 5.1.~~
=> Add getMaxPageNumber to PageNumberOutOfRangeException

CHANGELOG.md, src/Knp/Component/Pager/Paginator.php
This deprecation should allow an easier transition to version 3
=> deprecate not passing EventDispatcher to Paginator

docs/pager/config.md, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ODM/MongoDB/QueryBuilderSubscriber.php, src/Knp/Component/Pager/PaginatorInterface.php
For example if you want to take care about collation you need to add a 4th parameter on ->paginate() method like this:
```
return $paginator->paginate($builder, 1, 10, [Paginator::ODM_QUERY_OPTIONS => ['collation' => ['locale' => 'en', 'strength' => 2]]]);
```
=> Allow odmOptions to mongodb subscriber

composer.json
Symfony 5.1 is out of support [since last January](https://symfony.com/releases/5.1).
Let's drop it, and support only symfony libraries >= 5.2 in next minor version.
=> drop support for Symfony 5.1

.github/workflows/build.yaml, src/Knp/Component/Pager/Pagination/AbstractPagination.php
Fixes compatibility with PHP 8.1.
Unfortunately we cannot add PHP 8.1 in Github Actions matrix, because `laminas/laminas-code` v4.5 with PHP 8.1 support is not released yet.
=> Add compatibility with PHP 8.1

phpstan-baseline.neon, src/Knp/Component/Pager/Event/BeforeEvent.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/DBALQueryBuilderSubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/PaginationSubscriber.php, src/Knp/Component/Pager/Paginator.php, tests/Test/Fixture/Document/Image.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/DBALQueryBuilderTest.php, tests/Test/Pager/Subscriber/Paginate/PaginationSubscriberTest.php, tests/Test/Tool/BaseTestCase.php
=> fix dbal pagination count with groupBy

.github/workflows/build.yaml, .php-cs-fixer.php, composer.json, src/Knp/Component/Pager/ArgumentAccess/RequestArgumentAccess.php, src/Knp/Component/Pager/Event/AfterEvent.php, src/Knp/Component/Pager/Event/BeforeEvent.php, src/Knp/Component/Pager/Event/ItemsEvent.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/DBALQueryBuilderSubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, src/Knp/Component/Pager/Exception/PageNumberOutOfRangeException.php, src/Knp/Component/Pager/Pagination/SlidingPagination.php, src/Knp/Component/Pager/Paginator.php, src/Knp/Component/Pager/PaginatorInterface.php, tests/Test/Fixture/TestItem.php, tests/Test/Pager/Pagination/SlidingTest.php, tests/Test/Pager/Pagination/TraversableItemsTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/QueryTest.php, tests/Test/Pager/Subscriber/Paginate/Callback/CallbackTest.php, tests/Test/Pager/Subscriber/Sortable/Doctrine/ORM/QueryTest.php, tests/Test/Tool/BaseTestCaseMongoODM.php, tests/Test/Tool/BaseTestCaseORM.php, tests/Test/Tool/BaseTestCasePHPCRODM.php, tests/bootstrap.php
* drop support for PHP 8.0
* use language features of PHP 8.1
* fix "prefer-lowest" pipeline
[Rector](https://getrector.com/) was used to leverage language features of PHP 8.1.
Testing against PHP 8.4 is not possible yet since [`laminas/laminas-code`](https://github.com/laminas/laminas-code) which seems to be an indirect dependency does not allow PHP 8.4 yet.
Closes #338
=> Drop PHP 8.0

src/Knp/Component/Pager/Event/BeforeEvent.php, src/Knp/Component/Pager/Paginator.php, tests/Test/Pager/PaginatorTest.php
With this PR I'd like to suggest to pass the `$options` array with the `knp_pager.before` event in a way that makes it possible to modify the options from event subscribers.
Motivating use case:
I'd like to use values for the sort field parameter that do not expose implementation details in the URL. This is necessary to maintain stable URLs. 
For example, instead of using `blog.title+blog.published_date+blog.id` as a value in the sort query parameter, use `title`.
The translation from `title` to the actual sort criteria could take place in a `knp_pager.before` subscriber; however, it would need to be able to access the options, since I need to pass in information about which pagination use case is being executed (the mapping from query parameter to actual sort expression depends on it).
=> Pass `$options` in `knp_pager.before` event

src/Knp/Component/Pager/Event/ItemsEvent.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/FiltrationSubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Filtration/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ODM/MongoDB/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/ElasticaQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/PropelQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php, src/Knp/Component/Pager/Event/Subscriber/Sortable/SortableSubscriber.php, src/Knp/Component/Pager/Paginator.php, tests/Test/Pager/PaginatorTest.php, tests/Test/Pager/Subscriber/Filtration/Doctrine/ORM/QueryTest.php, tests/Test/Pager/Subscriber/Sortable/ArraySubscriberTest.php
This makes it possible for `knp_pager.items` event subscribers to access the pagination parameters, without having to be wired up by a dedicated `knp_pager.before` handler.
=> Pass `ArgumentAccess` with the `knp_pager.items` event

src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/DBALQueryBuilderSubscriber.php, tests/Test/Pager/Subscriber/Paginate/Doctrine/DBALQueryBuilderTest.php
SQL Server does not allow ORDER BY clauses in sub-queries unless they are limited by a TOP / OFFSET clause which we don't want to do when getting an item count.
=> Remove order by clause from the item count query.
